version: '3.0'
services:
  users:
    build: ./usersService
    ports:
      - "5000:5000"
    volumes:
      - ./usersService/src:/usr/src/app/src
      - ./usersService/package.json:/usr/src/app/package.json
      - ./usersService/node_modules:/usr/src/app/node_modules
  matchs:
    build: ./matchsService
    ports:
      - "5001:5000"
    depends_on:
      - users
    volumes:
      - ./matchsService/src:/usr/src/app/src
      - ./matchsService/package.json:/usr/src/app/package.json
      - ./matchsService/node_modules:/usr/src/app/node_modules