version: '3.0'
services:
  proxi:
    image: nginx
    volumes:
      - ./proxi:/etc/nginx:ro
    ports:
      - "80:80"
    depends_on:
      - users
      - auth
      - matchs
  auth:
    build: ./authService
    ports:
      - "5002:5000"
    depends_on:
      - users
    volumes:
      - ./authService/src:/usr/src/app/src
      - ./authService/package.json:/usr/src/app/package.json
      - ./authService/node_modules:/usr/src/app/node_modules
  users:
    build: ./usersService
    ports:
      - "5000:5000"
    volumes:
      - ./usersService/src:/usr/src/app/src
      - ./usersService/package.json:/usr/src/app/package.json
      - ./usersService/node_modules:/usr/src/app/node_modules
      - ./usersService/db/migrations:/usr/src/app/db/migrations
  matchs:
    build: ./matchsService
    ports:
      - "5001:5000"
    depends_on:
      - users
    volumes:
      - ./matchsService/src:/usr/src/app/src
      - ./matchsService/package.json:/usr/src/app/package.json
      - ./matchsService/node_modules:/usr/src/app/node_modules
      - ./matchsService/db/migrations:/usr/src/app/db/migrations